[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SKIP_ENV_VALIDATION = "true"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x"
  PRISMA_QUERY_ENGINE_LIBRARY = "rhel-openssl-1.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client", "prisma", "mysql2"]
  node_bundler = "esbuild"
