[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
SKIP_ENV_VALIDATION = "true"
NODE_VERSION = "18"
PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client", "prisma", "mysql2"]
  node_bundler = "esbuild"
